/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/chineseGuy2.glb -o components/Gltf/ChineseGuy2.tsx 
*/

import * as THREE from "three";
import React, { JSX, useEffect, useRef } from "react";
import { useGraph, useLoader } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";
import { TextureLoader } from "three";

type ActionName =
    | "bakedMouseAnimation"
    | "mouseAnimation"
    | "bakedTyping"
    | "fixTyping"
    | "typing"
    | "bakedEyeAnimation"
    | "bakedFaceTyping.001"
    | "eyeAnimation";

interface GLTFAction extends THREE.AnimationClip {
    name: ActionName;
}

type GLTFResult = GLTF & {
    nodes: {
        features001: THREE.SkinnedMesh;
        head001: THREE.SkinnedMesh;
        leftEye001: THREE.SkinnedMesh;
        rightEye001: THREE.SkinnedMesh;
        body: THREE.SkinnedMesh;
        hairs: THREE.SkinnedMesh;
        shirt: THREE.SkinnedMesh;
        computer: THREE.Mesh;
        deskWalls: THREE.Mesh;
        desk: THREE.Mesh;
        chair: THREE.Mesh;
        computerScreenLight: THREE.Mesh;
        mouse006: THREE.Mesh;
        mixamorigHips: THREE.Bone;
        Ctrl_Master: THREE.Bone;
        root: THREE.Bone;
        ["MCH-eyeparentL"]: THREE.Bone;
        ["MCH-eyeparentR"]: THREE.Bone;
        ["MCH-lip_armBL001"]: THREE.Bone;
        ["MCH-lip_armBR001"]: THREE.Bone;
        ["MCH-lip_armTL001"]: THREE.Bone;
        ["MCH-lip_armTR001"]: THREE.Bone;
        neutral_bone: THREE.Bone;
        Ctrl_ArmPole_IK_Left: THREE.Bone;
        Ctrl_Hand_IK_Left: THREE.Bone;
        Ctrl_ArmPole_IK_Right: THREE.Bone;
        Ctrl_Hand_IK_Right: THREE.Bone;
        Ctrl_Foot_IK_Left: THREE.Bone;
        Ctrl_LegPole_IK_Left: THREE.Bone;
        Ctrl_Foot_IK_Right: THREE.Bone;
        Ctrl_LegPole_IK_Right: THREE.Bone;
    };
    animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { scene, animations } = useGLTF("/chineseGuy2.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes } = useGraph(clone) as unknown as GLTFResult;
    const { actions } = useAnimations(animations, group);

    const textureChair = useLoader(TextureLoader, "bakeChair.jpg");
    const textureDesk = useLoader(TextureLoader, "bakedDesk.jpg");
    const textureDeskWalls = useLoader(TextureLoader, "bakedDeskWalls.jpg");
    const textureComputer = useLoader(TextureLoader, "bakedComputer.jpg");
    const textureHead = useLoader(TextureLoader, "bakedHead.jpg");
    const textureHairs = useLoader(TextureLoader, "bakedHairs.jpg");
    const textureShirt = useLoader(TextureLoader, "bakedShirt.jpg");
    const textureHeadRoughness = useLoader(
        TextureLoader,
        "bakedHeadRoughness.jpg"
    );
    textureHead.flipY = false;
    textureHeadRoughness.flipY = false;
    textureHead.colorSpace = THREE.SRGBColorSpace;
    textureHeadRoughness.colorSpace = THREE.SRGBColorSpace;
    const textureFeatures = useLoader(TextureLoader, "bakedFeatures.jpg");
    textureFeatures.flipY = false;
    textureFeatures.colorSpace = THREE.SRGBColorSpace;
    const textureBody = useLoader(TextureLoader, "bakedBody.jpg");
    textureBody.flipY = false;
    textureBody.colorSpace = THREE.SRGBColorSpace;
    const textures = [
        textureChair,
        textureDesk,
        textureDeskWalls,
        textureComputer,
        textureHairs,
        textureShirt,
    ];
    textures.forEach((texture) => {
        texture.flipY = false;
        texture.colorSpace = THREE.SRGBColorSpace;
    });
    const textureMaterials = Array(6)
        .fill(0)
        .map((_, i) => {
            return new THREE.MeshBasicMaterial({ map: textures[i] });
        });
    const textureHeadMaterial = new THREE.MeshBasicMaterial({
        map: textureHead,
    });
    const textureFeaturesMaterial = new THREE.MeshBasicMaterial({
        map: textureFeatures,
    });
    const textureBodyMaterial = new THREE.MeshBasicMaterial({
        map: textureBody,
    });
    const textureComputerScreen = new THREE.MeshStandardMaterial({
        emissive: new THREE.Color("9CD0E7"),
        emissiveIntensity: 4,
    });

    nodes.chair.material = textureMaterials[0];
    nodes.desk.material = textureMaterials[1];
    nodes.deskWalls.material = textureMaterials[2];
    nodes.computer.material = textureMaterials[3];
    nodes.head001.material = textureHeadMaterial;
    nodes.features001.material = textureFeaturesMaterial;
    nodes.leftEye001.material = textureFeaturesMaterial;
    nodes.rightEye001.material = textureFeaturesMaterial;
    nodes.body.material = textureBodyMaterial;
    nodes.shirt.material = textureMaterials[5];
    nodes.hairs.material = textureMaterials[4];
    nodes.computerScreenLight.material = textureComputerScreen;

    useEffect(() => {
        console.log("actions", actions);
        actions["bakedTyping"]?.play();
        actions["bakedFaceTyping.001"]?.play();
        actions["mouseAnimation"]?.play();
        actions["bakedEyeAnimation"]?.play();
    }, [actions]);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Armature002" position={[-1.81, 0.129, 1.051]}>
                    <primitive object={nodes.mixamorigHips} />
                    <primitive object={nodes.Ctrl_Master} />
                    <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
                    <primitive object={nodes.Ctrl_Hand_IK_Left} />
                    <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
                    <primitive object={nodes.Ctrl_Hand_IK_Right} />
                    <primitive object={nodes.Ctrl_Foot_IK_Left} />
                    <primitive object={nodes.Ctrl_LegPole_IK_Left} />
                    <primitive object={nodes.Ctrl_Foot_IK_Right} />
                    <primitive object={nodes.Ctrl_LegPole_IK_Right} />
                    <skinnedMesh
                        name="body"
                        geometry={nodes.body.geometry}
                        material={nodes.body.material}
                        skeleton={nodes.body.skeleton}
                    />
                    <skinnedMesh
                        name="hairs"
                        geometry={nodes.hairs.geometry}
                        material={nodes.hairs.material}
                        skeleton={nodes.hairs.skeleton}
                    />
                    <skinnedMesh
                        name="shirt"
                        geometry={nodes.shirt.geometry}
                        material={nodes.shirt.material}
                        skeleton={nodes.shirt.skeleton}
                    />
                </group>
                <mesh
                    name="computer"
                    geometry={nodes.computer.geometry}
                    material={nodes.computer.material}
                    position={[-5.239, 3.858, 5.106]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                />
                <mesh
                    name="deskWalls"
                    geometry={nodes.deskWalls.geometry}
                    material={nodes.deskWalls.material}
                    position={[-5.239, 3.858, 5.106]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                />
                <mesh
                    name="desk"
                    geometry={nodes.desk.geometry}
                    material={nodes.desk.material}
                    position={[-5.239, 3.858, 5.106]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                />
                <mesh
                    name="chair"
                    geometry={nodes.chair.geometry}
                    material={nodes.chair.material}
                    position={[-5.239, 3.858, 5.106]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                />
                <mesh
                    name="computerScreenLight"
                    geometry={nodes.computerScreenLight.geometry}
                    material={nodes.computerScreenLight.material}
                    position={[-1.418, 4.564, 4.922]}
                    scale={1.123}
                />
                <mesh
                    name="mouse006"
                    geometry={nodes.mouse006.geometry}
                    material={nodes.mouse006.material}
                    position={[-3.32, 3.066, 2.968]}
                    rotation={[0, 0.244, 0]}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/chineseGuy2.glb");
